name: Setup dependencies
description: Sets up and install all common dependencies

runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}
      cache: 'pip'
  - name: Set up Node JS
    uses: actions/setup-node@v3
    with:
      node-version: '.nvmrc'
      cache: 'npm'
  - name: Install Learning Observer dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pycodestyle
      npm ci
