- name: Set Environment Variables
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  tasks:
    - name: Read credentials
      include_vars:
        file: ../../tasks/settings/CREDS.YAML

    - name: Assign variables
      set_fact:
        yaml_file: "OS_ENV_VARS.YAML"
        yaml_dir: "{{ flock_config }}/config/{{ inventory_hostname }}/yaml"
       
    - name: Read repository configuration
      include_vars:
        file: "{{ yaml_dir }}/{{ yaml_file }}"

    - name: Populate /etc/environment
      lineinfile:
        path: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ os_environment }}"