'''This file lists all the options for LanguageTool (LT)
so we can query specific items.

Note that all features are calculated at once when
querying LT. Listing all the features here allows
dashboards pull out specific items from the returned
query.

TODO figure out the best data structure for storing
the available features
'''

# Each tuple in AVAILABLE_ITEMS contains the full path of
# the categories.
AVAILABLE_ITEMS = [
    ('Capitalization', 'Unnecessary capitalization'),
    ('Capitalization', 'Acronyms'),
    ('Capitalization', 'Abbreviations'),
    ('Capitalization', 'Hyphenated Letter Case'),
    ('Capitalization', 'Sentence Start'),
    ('Capitalization', 'Proper noun case'),
    ('Capitalization', 'First person singular caps'),
    ('Grammar', 'Extra function word'),
    ('Grammar', 'Nonstandard copula'),
    ('Grammar', 'Tag question error'),
    ('Grammar', 'Missing function word'),
    ('Grammar', 'Wrong verb tense'),
    ('Grammar', 'Conjunction error'),
    ('Grammar', 'Bare possessive'),
    ('Grammar', 'Wrong word order'),
    ('Grammar', 'Pronoun/antecedent agreement'),
    ('Grammar', 'Plural error'),
    ('Grammar', 'Missing content word'),
    ('Grammar', 'Repeated words'),
    ('Grammar', 'Pronoun case'),
    ('Grammar', 'Article error'),
    ('Grammar', 'Complement error'),
    ('Grammar', 'Sentence fragment'),
    ('Grammar', 'Comparative error'),
    ('Grammar', 'Superlative error'),
    ('Grammar', 'Tense error'),
    ('Grammar', 'Wrong verb form'),
    ('Grammar', 'Wrong part of speech'),
    ('Grammar', 'Subject/verb agreement'),
    ('Grammar', 'Wrong past participle'),
    ('Grammar', 'Negation error'),
    ('Possible Typo', 'Misplaced space'),
    ('Possible Typo', 'Missing space'),
    ('Possible Typo', 'Incorrect plural possessive'),
    ('Possible Typo', 'Wrong case'),
    ('Possible Typo', 'Missing hyphen'),
    ('Possible Typo', 'Wrong contraction'),
    ('Possible Typo', 'Possessive as contraction'),
    ('Possible Typo', 'Wrong letter'),
    ('Possible Typo', 'Terminology'),
    ('Possible Typo', 'Reversed letters'),
    ('Possible Typo', 'Possessive as plural'),
    ('Possible Typo', 'Extra space'),
    ('Possible Typo', 'Bare possessive'),
    ('Possible Typo', 'Missing punctuation'),
    ('Possible Typo', 'Extra letter'),
    ('Possible Typo', 'Missing period'),
    ('Possible Typo', 'Plural as possessive'),
    ('Possible Typo', 'Repeated words'),
    ('Possible Typo', 'Contraction without apostrophe'),
    ('Possible Typo', 'Missing letter'),
    ('Punctuation', 'Missing end punctuation'),
    ('Punctuation', 'Oxford comma'),
    ('Punctuation', 'Conjunction'),
    ('Punctuation', 'Abbreviation'),
    ('Punctuation', 'Comparison'),
    ('Punctuation', 'Restrictive modifier'),
    ('Punctuation', 'Compound sentence'),
    ('Punctuation', 'Compound adjective'),
    ('Punctuation', 'Sentence modifier'),
    ('Punctuation', 'Vocative'),
    ('Semantics', 'Date inconsistency'),
    ('Semantics', 'Meaning mismatch'),
    ('Spelling', 'Number in Name'),
    ('Spelling', 'Misused idiom'),
    ('Spelling', 'Missing letter'),
    ('Spelling', 'Extra letter'),
    # ('Spelling', 'Possible Typo'),
    ('Spelling', 'Added or dropped t/ed'),
    ('Spelling', 'Phonetic spelling'),
    ('Spelling', 'Inconsistent Spelling'),
    ('Spelling', 'Homonym'),
    ('Spelling', 'Unknown word'),
    ('Style', 'Formality'),
    ('Style', 'Word choice'),
    ('Style', 'Repetition'),
    ('Style', 'Wikipedia'),
    ('Style', 'British English'),
    ('Style', 'Readability'),
    ('Style', 'Profanity'),
    ('Style', 'Awkward language'),
    ('Style', 'Redundancy'),
    ('Style', 'Informal'),
    ('Style', 'Indian English Only'),
    ('Typography', 'Roman Numerals'),
    ('Typography', 'Math'),
    ('Typography', 'Date format'),
    ('Typography', 'Missing space'),
    ('Typography', 'Repeated punctuation'),
    ('Typography', 'Headings'),
    ('Typography', 'Redundant punctuation'),
    ('Typography', 'Extra whitespace'),
    ('Typography', 'Paragraph Indent'),
    ('Typography', 'Time format'),
    ('Typography', 'Special character'),
    ('Typography', 'Currency'),
    ('Usage', 'Confused words'),
    ('Usage', 'Missing preposition'),
    ('Usage', 'Misused idiom'),
    ('Usage', 'Wrong preposition'),
    ('Usage', 'Wrong verb'),
    ('Usage', 'Extra preposition'),
    ('Word Boundaries', 'Missing hyphen'),
    ('Word Boundaries', 'Extra space'),
    ('Word Boundaries', 'Prefix as word'),
    ('Word Boundaries', 'Missing space')
]

CATEGORIES = [
    'Grammar', 'Semantics', 'Style', 'Usage',
    'Capitalization', 'Possible Typo', 'Punctuation',
    'Spelling', 'Typography', 'Word Boundaries'
]
