name: Continuous Integration

on: [push]

defaults:
  run:
    shell: bash

jobs:
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        module: ["learning_observer/", "modules/writing_observer/"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Linting ${{ matrix.module }}
      uses: ./.github/actions/lint
      id: lo-lint
      with:
        module-dir: ${{ matrix.module }}
        python-version: "3.10"

  test-lo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Learning Observer
      uses: ./.github/actions/install-dependencies
      with:
        python-version: "3.10"
    - name: Unit Test Learning Observer
      run: pytest --doctest-modules learning_observer/learning_observer
  
  test-modules:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        module: ["modules/writing_observer", "modules/wo_highlight_dashboard"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Learning Observer
      uses: ./.github/actions/install-dependencies
      with:
        python-version: "3.10"
    - name: Install ${{ matrix.module }} dependencies
      run: |
        if [ -d "${{ matrix.module }}" ] && [ -f "${{ matrix.module }}/requirements.txt" ]; then
          pip install -r "${{ matrix.module }}/requirements.txt"
        fi
        pip install -e "${{ matrix.module }}"
    - name: Testing ${{ matrix.module }}
      run: |
        pytest ${{ matrix.module }}
