name: Pytest

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Script
      uses: actions/github-script@v7.0.1
      with:
        # The script to run
        script: |
            const shortSHA = context.sha.substring(0, 7);
            const date = new Date().toISOString().split('T')[0]; // Gets date in YYYY-MM-DD format
            const formattedDate = date.replace(/-/g, '.'); // Replaces '-' with '.'
            const tagName = `${formattedDate}-${shortSHA}`;
            
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: context.sha
            })
